# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: dotnet build 
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: npm install
        run: npm install
        working-directory: bianca-fiorella

      - name: vite build
        run: VITE_OUTDIR=${{env.DOTNET_ROOT}}/myapp npm run buildci
        working-directory: bianca-fiorella

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: az login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E63CEAF7763E4811B2162242D9C494C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CA94E47B8D25402AAAD6243D460442A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0C79696A5FC40A09B6B9621625EF958 }}

      - name: az webapp deploy
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'biancafiorella'
          slot-name: 'Production'
          package: .
          